"""Module 4 analysis — prompt-order permutation sensitivity.

Compares satisfaction rates between base prompts and their order-permuted
variants (generated by ``compscale/generation/permute_prompts.py``). For each
base prompt, computes the per-permutation delta-satisfaction and reports the
mean absolute delta per type.

Gate (plan): mean |delta satisfaction| per base prompt < 0.10. If violated,
prompt order matters materially and we should either sample multiple orderings
per prompt in the full benchmark or promote order-sensitivity to a first-class
finding.

Writes ``compscale/sanity/order_permutation_report.json``.
"""

import argparse
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ORDER_GATE = 0.10


def _aggregate_by_prompt(results):
    """Mean satisfaction_rate per prompt_id."""
    by_pid = defaultdict(list)
    for r in results:
        by_pid[r["prompt_id"]].append(r["satisfaction_rate"])
    return {pid: float(np.mean(vals)) for pid, vals in by_pid.items()}


def _prompt_type(results, pid):
    for r in results:
        if r["prompt_id"] == pid and r.get("type"):
            return r["type"]
    return None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base_results", required=True,
                        help="vlm_verify results over the four Module-1 pilot files")
    parser.add_argument("--perm_results", required=True,
                        help="vlm_verify results over order_pilot.json")
    parser.add_argument("--order_pilot",
                        default="compscale/benchmark/prompts/order_pilot.json",
                        help="Order pilot JSON (to recover base_id mapping)")
    parser.add_argument("--output",
                        default="compscale/sanity/order_permutation_report.json")
    parser.add_argument("--gate", type=float, default=ORDER_GATE)
    args = parser.parse_args()

    base = json.loads(Path(args.base_results).read_text())
    perm = json.loads(Path(args.perm_results).read_text())
    order_pilot = json.loads(Path(args.order_pilot).read_text())
    perm_meta = {p["id"]: p for p in order_pilot}

    base_mean = _aggregate_by_prompt(base)
    perm_mean = _aggregate_by_prompt(perm)

    per_type = defaultdict(list)
    per_base = defaultdict(lambda: {"base_sat": None, "perm_sats": [], "type": None})

    for perm_id, perm_sat in perm_mean.items():
        meta = perm_meta.get(perm_id)
        if not meta:
            continue
        base_id = meta["base_id"]
        ctype = meta["type"]
        base_sat = base_mean.get(base_id)
        if base_sat is None:
            continue
        per_base[base_id]["base_sat"] = base_sat
        per_base[base_id]["perm_sats"].append(perm_sat)
        per_base[base_id]["type"] = ctype

    per_base_report = []
    for base_id, info in per_base.items():
        if info["base_sat"] is None or not info["perm_sats"]:
            continue
        deltas = [abs(s - info["base_sat"]) for s in info["perm_sats"]]
        mean_abs_delta = float(np.mean(deltas))
        per_type[info["type"]].append(mean_abs_delta)
        per_base_report.append({
            "base_id": base_id,
            "type": info["type"],
            "base_sat": round(info["base_sat"], 4),
            "perm_sats": [round(s, 4) for s in info["perm_sats"]],
            "mean_abs_delta": round(mean_abs_delta, 4),
        })

    per_type_summary = {
        t: {
            "n_base_prompts": len(deltas),
            "mean_abs_delta": float(np.mean(deltas)),
            "max_abs_delta": float(np.max(deltas)),
            "gate": args.gate,
            "status": "pass" if float(np.mean(deltas)) < args.gate else "fail",
        }
        for t, deltas in per_type.items()
    }

    overall_status = (
        "pass" if per_type_summary and all(s["status"] == "pass"
                                            for s in per_type_summary.values())
        else "fail"
    )

    report = {
        "gate": args.gate,
        "overall_status": overall_status,
        "per_type": per_type_summary,
        "per_base_prompt": per_base_report,
    }
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2))

    print("Per-type order-permutation sensitivity:")
    for t, s in per_type_summary.items():
        print(
            f"  {t}: n={s['n_base_prompts']} "
            f"mean|delta|={s['mean_abs_delta']:.3f} "
            f"max|delta|={s['max_abs_delta']:.3f} [{s['status']}]"
        )
    print(f"\nOverall status: {overall_status}")
    print(f"Report written to {out}")


if __name__ == "__main__":
    main()
